// Find-or-insert helper for AI-generated recipes. Without this, every
// "Regenerate this week's meals" click creates 21 new rows even when the
// model produces the same recipe names — the recipes table grows
// without bound. With it, repeat generations reuse rows and the table
// stays compact.
//
// Match key: (owner_id, name, kcal, protein) + the "auto-generated" tag.
// We don't dedup user-created recipes — only the bulk planner output.

import type { SupabaseClient } from "@supabase/supabase-js";
import type { GeneratedRecipe } from "@/lib/ai/prompts/recipe";

export async function upsertAutoGeneratedRecipe(args: {
  supabase: SupabaseClient;
  userId: string;
  recipe: GeneratedRecipe;
  photoUrl: string | null;
  defaultServings: number;
}): Promise<string | null> {
  const { supabase, userId, recipe, photoUrl, defaultServings } = args;

  // Look for an existing auto-generated recipe with the same name + macros
  // for this user. Using kcal + protein as the secondary signal catches
  // intentional remixes (different macros = different recipe).
  const { data: existing } = await supabase
    .from("recipes")
    .select("id")
    .eq("owner_id", userId)
    .eq("name", recipe.name)
    .eq("kcal", recipe.kcal)
    .eq("protein", recipe.protein)
    .contains("tags", ["auto-generated"])
    .order("created_at", { ascending: true })
    .limit(1)
    .maybeSingle();

  if (existing) return existing.id as string;

  const { data: inserted, error } = await supabase
    .from("recipes")
    .insert({
      owner_id: userId,
      name: recipe.name,
      photo_url: photoUrl,
      source_url: null,
      ingredients_json: recipe.ingredients,
      steps_json: recipe.steps,
      kcal: recipe.kcal,
      protein: recipe.protein,
      carbs: recipe.carbs,
      fat: recipe.fat,
      time_min: recipe.time_min,
      servings: recipe.servings ?? defaultServings,
      family_notes_json: recipe.family_modifications ?? [],
      tips_json: recipe.tips ?? [],
      tags: [...new Set([...(recipe.tags ?? []), "auto-generated"])],
    })
    .select("id")
    .single();

  if (error || !inserted) return null;
  return inserted.id as string;
}
